openapi: 3.1.0
info:
  version: 1.0.0
  title: Parcelamento 100%
  #termsOfService: https://example.com/terms/
  #contact:
    #email: contact@example.com
    #url: http://example.com/contact
  #license:
    #name: Apache 2.0
    #url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://logodownload.org/wp-content/uploads/2019/10/digio-logo-0-2.png
  description: >
    Conseguir cadastrar possíveis taxas e faixa de crédito (limite)     
    [CST-1681](https://bancocbss.atlassian.net/browse/CST-1681).
#tags:
#  - name: Cadastro de Faixa
#    description: Cadastro de taxas e faixa de crédito (limite).
#servers:
#  - url: https://{tenant}/api/v1
#    variables:
#      tenant:
#        default: www
#        description: Your tenant id
#  - url: https://example.com/api/v1
paths:
  /users/{username}:
    $ref: paths/users_{username}.yaml
#  /echo:
#    $ref: paths/echo.yaml
#  /pathItem:
#    $ref: paths/pathItem.yaml
#  /pathItemWithExamples:
#    $ref: paths/pathItemWithExamples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
